---
# Location where configuration files will be stored.
config_dir: '~'

#
#   This is the simplyfied configuration file.
#   For advanced configuration see `advanced.config.yml`
#

#    _____ _           _____             
#   |_   _|_|_____ ___|__   |___ ___ ___ 
#     | | | |     | -_|   __| . |   | -_|
#     |_| |_|_|_|_|___|_____|___|_|_|___|
# Your timezone for all services.
ur_timezone: "Europe/Kyiv"

#    _____     _                 _   ____  _____ _____ 
#   |  |  |___| |_ ___ _ _ ___ _| | |    \|   | |   __|
#   |  |  |   | . | . | | |   | . |_|  |  | | | |__   |
#   |_____|_|_|___|___|___|_|_|___|_|____/|_|___|_____| Dont't use with .Tech.DNS at the same time!
# Unbound DNS configuration.
unbound_dns_enable: true                        # Set true to enable Unbound DNS. Don't use with Technition DNS at the same time!

#    _____ _ _____     _     
#   |  _  |_|  |  |___| |___ 
#   |   __| |     | . | | -_|
#   |__|  |_|__|__|___|_|___| Dont't use with .Tech.DNS at the same time!
# Pi-hole configuration.
pihole_enable: true                             # Set true to enable Pi-Hole. Don't use with Technition DNS at the same time!
pihole_with_unbound: true                       # Enable Pi-Hole to use Unbound DNS as upstream DNS server.
pihole_password: "gagaZush"                     # !Change this password!

#      _____         _     ____  _____ _____   
#     |_   _|___ ___| |_  |    \|   | |   __|  
#    _  | | | -_|  _|   |_|  |  | | | |__   |_ 
#   |_| |_| |___|___|_|_|_|____/|_|___|_____|_|  Don't use with PiHole at the same time!
# Technitium DNS Server configuration.
tech_dns_enable: false                          # Set true to enable Technitium DNS. Don't use with Pi-hole at the same time!
tech_dns_password: "gagaZush"                   # !Change this password!

#    _____             _____ _____ _____ 
#   |     |___ ___ ___|  |  |  _  |   | |
#   |  |  | . | -_|   |  |  |   __| | | |
#   |_____|  _|___|_|_|\___/|__|  |_|___|
#         |_|
# OpenVPN Server configuration.
ovpn_server_enable: false                       # Set true to enable OpenVPN server
ovpnui_password: "gagaZush"                     # !Change this password!

# OpenVPN Client configuration for qBittorrent only. OpenVPN server is not required.
ovpn_client_enable: false                       # Set true to enable internal OpenVPN client used for qBittorrent. OpenVPN server is not required.
ovpn_client_cert: "example-client.ovpn"         # Set your ovpn-client certificate name
ovpn_client_allowed_subnet: "192.168.88.0/24"   # Allowed subnet for ovpn-client. You must have your local network defined here.

#    _ _ _ _         _____               _ 
#   | | | |_|___ ___|   __|_ _ ___ ___ _| |
#   | | | | |  _| -_|  |  | | | .'|  _| . |
#   |_____|_|_| |___|_____|___|__,|_| |___|
# WireGuard Server configuration.
wireguard_server_enable: false                  # Set true to enable WireGuard
wireguard_password: "gagaZush"                  # !Change this password!

#    _____         _       _ 
#   |  _  |___ ___| |_ ___|_|___ ___ ___ 
#   |   __| . |  _|  _| .'| |   | -_|  _|
#   |__|  |___|_| |_| |__,|_|_|_|___|_|  
# Portainer configuration.
portainer_enable: true                          # Set true to enable Portainer

#        _____ _ _   _____                     _   
#    ___| __  |_| |_|_   _|___ ___ ___ ___ ___| |_ 
#   | . | __ -| |  _| | | | . |  _|  _| -_|   |  _|
#   |_  |_____|_|_|   |_| |___|_| |_| |___|_|_|_|  
#     |_|                                         
# QbitTorrent configuration.
qbittorrent_enable: false                       # Set true to enable qBittorrent and its WebUI
qbittorrent_default_password: admin/adminadmin  # !Change this password wia WebUI!
# Local VPN configuration. Allows qBittorrent runs through VPN client connection.
qbittorrent_inside_vpn: false                   # Set true to route qBitTorrent traffic via internal OpenVPN client

#    _____         _ _               
#   |     |___ ___|_| |_ ___ ___ ___ 
#   | | | | . |   | |  _| . |  _|_ -|
#   |_|_|_|___|_|_|_|_| |___|_| |___|
# Raspberry-monitoring configuration.
monitoring_enable: true                         # Set true to enable base Raspberry monitoring
monitoring_grafana_admin_password: "admin"      # Is only used the first time when Grafana starts up

# OpenVPN monitoring configuration.             # Requires `monitoring_enable`
openvpn_monitoring_enable: false                # Set true to enable OpenVPN server Grafana dashboard

# PiKVM monitoring configuration.               # Requires `monitoring_enable`
pikvm_monitoring_enable: false                  # Set true to enable PiKVM Grafana dashboard

# AirGradient monitoring configuration.         # Requires `monitoring_enable`
airgradient_monitoring_enable: false            # Set true to enable Airgradient Grafana dashboard

# Starlink monitoring configuration.            # Requires `monitoring_enable`
starlink_monitoring_enable: false               # Set true to enable StarLink dishy Grafana dashboard

# Shelly Plug monitoring configuration.         # Set true to enable Shelly Plug Grafana dashboard
shelly_plug_monitoring_enable: false            # Set true or false
