---
- name: Create OpenVPN client folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/openvpn-client"
    state: directory
    mode: 0755
  become: false

- name: Synchronize OpenVPN client directory.
  ansible.posix.synchronize:
    src: openvpn-client
    dest: "{{ config_dir }}/"
    delete: false
    recursive: true
    perms: false
  become: false

- name: Copy OpenVPN client docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: "{{ config_dir }}/openvpn-client/{{ item.dest }}"
    mode: 0740
  loop:
    - src: ovpn_client-docker-compose.yml.j2
      dest: docker-compose.yml
  become: false
  notify: Restart OpenVPN client

- name: Ensure OpenVPN client is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/openvpn-client/"
    build: false
  become: false
  environment:
    DOCKER_CLIENT_TIMEOUT: '180'
    COMPOSE_HTTP_TIMEOUT: '180'
