---
- name: Create Portainer folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/portainer"
    state: directory
    mode: 0755
  become: false

- name: Copy Portainer docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/portainer-docker-compose.yml.j2
    dest: "{{ config_dir }}/portainer/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart portainer

# TODO: The first time this playbook is run, the `pi` user may not be added
# to the `docker` group, so this task may fail.
- name: Ensure Portainer is running.
  community.docker.docker_compose:
    project_src: "{{ config_dir }}/portainer/"
    build: false
  become: false
