---
- name: Create qbitTorrent folder on Pi.
  ansible.builtin.file:
    path: "{{ config_dir }}/qbittorrent/downloads"
    state: directory
    mode: 0755
  become: false

- name: Pull latest qBitTorrent Docker image
  community.general.docker_image:
    source: pull
    name: lscr.io/linuxserver/qbittorrent
    tag: latest
  become: false

- name: Copy qbitTorrent docker-compose template to Pi.
  ansible.builtin.template:
    src: templates/qbittorrent-docker-compose.yml.j2
    dest: "{{ config_dir }}/qbittorrent/docker-compose.yml"
    mode: '0640'
  become: false
  notify: Restart qbitTorrent

- name: Ensure qbitTorrent is running.
  community.docker.docker_compose_v2:
    project_src: "{{ config_dir }}/qbittorrent/"
    build: false
  become: false
  environment:
    DOCKER_CLIENT_TIMEOUT: '180'
    COMPOSE_HTTP_TIMEOUT: '180'